name: Build and Upload Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs

      - name: Fetch LFS files
        run: |
          git lfs install
          git lfs pull

      - name: Verify Model File Exists
        run: ls -lah fall_detection_model.joblib

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}"  
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME_LOWER:latest --push .
