name: Test python code

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest
